services:
  db_postgres_container:
    image: postgres
    container_name: db_postgres_container
    restart: always
    ports:
      - 1234:5432
    env_file:
      - .env
    volumes:
      - db_postgres_volume:/var/lib/postgresql/data
      
  node_app_sorteador:
    container_name: node_app_sorteador
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db_postgres_container
    env_file:
      - .env

volumes:
  db_postgres_volume:

